---
- op: replace
  path: /spec/template/spec/source/repoURL
  value: https://github.com/gabemontero-appstudio-test-org/infra-deployments.git
- op: replace
  path: /spec/template/spec/source/targetRevision
  value: preview-pipeline-service-aqrz
