---
- op: replace
  path: /spec/source/repoURL
  value: https://github.com/gabemontero-appstudio-test-org/infra-deployments.git
- op: replace
  path: /spec/source/targetRevision
  value: preview-override-tekton-ctrl-img-salk
